# Generated by Django 4.1.3 on 2023-01-02 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mensajes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('leido', models.BooleanField(default=False)),
                ('usuarioEmisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioEmisor', to=settings.AUTH_USER_MODEL)),
                ('usuarioReceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioReceptor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
